# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DigiGoalExamimation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DigiGoalExamimation
  pod 'Socket.IO-Client-Swift'

end

post_install do |installer|

  installer.pods_project.targets.each do |target|

    # Fix xcode 15 error
    target.build_configurations.each do |config|
      if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
        xcconfig_path = config.base_configuration_reference.real_path
        IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
    end
    
  end
  
end